builds:
  - main: cmd/benthos/main.go
    binary: benthos
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
archive:
  format: tar.gz
  files:
    - README.md
    - CHANGELOG.md
    - LICENSE
    - config/*
    - config/**/*
    - docs/*
    - docs/**/*
dist: target/dist
changelog:
  filters:
    exclude:
      - .*
release:
  github:
    owner: NamelessHH
    name: benthos
  disable: false
